import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1740000000000 implements MigrationInterface {
    name = 'InitialSchema1740000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."roles_code_enum" AS ENUM('admin', 'student', 'teacher', 'employee')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "code" "public"."roles_code_enum" NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "tokenHash" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "directions" ("id" SERIAL NOT NULL, "code" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_0670062704473c1e1f529330c88" UNIQUE ("code"), CONSTRAINT "PK_f619ca47644a835bd091e8b9814" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_uploads_scheduletype_enum" AS ENUM('student', 'teacher', 'auditory', 'consultation')`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_uploads_parsestatus_enum" AS ENUM('success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "schedule_uploads" ("id" SERIAL NOT NULL, "scheduleType" "public"."schedule_uploads_scheduletype_enum" NOT NULL, "originalFileName" character varying NOT NULL, "storedFileName" character varying NOT NULL, "fileUrl" character varying NOT NULL, "mimeType" character varying NOT NULL, "fileSize" integer NOT NULL, "groupName" character varying, "facultyName" character varying, "parseStatus" "public"."schedule_uploads_parsestatus_enum" NOT NULL DEFAULT 'success', "parseErrors" jsonb, "parseWarnings" jsonb, "lessonsCount" integer NOT NULL DEFAULT '0', "periodStart" character varying, "periodEnd" character varying, "uploadedById" integer NOT NULL, "uploadedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17921b8f9041b7e516401db1b15" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedules_scheduletype_enum" AS ENUM('student', 'teacher', 'auditory', 'consultation')`);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" SERIAL NOT NULL, "scheduleType" "public"."schedules_scheduletype_enum" NOT NULL, "groupId" integer, "teacherId" integer, "uploadId" integer, "validFrom" date NOT NULL, "validTo" date NOT NULL, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, CONSTRAINT "PK_1a023685ac2b051b4e557b0b280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lesson_types_code_enum" AS ENUM('lecture', 'practice', 'lab', 'credit', 'kr_defense', 'special')`);
        await queryRunner.query(`CREATE TABLE "lesson_types" ("id" SERIAL NOT NULL, "code" "public"."lesson_types_code_enum" NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_87c3ff65eb002ef8ef4a80c9911" UNIQUE ("code"), CONSTRAINT "PK_e94b534abe91cc97a2234e65e44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "rooms" ("id" SERIAL NOT NULL, "building" character varying, "number" character varying NOT NULL, "name" character varying, "isOnline" boolean NOT NULL DEFAULT false, "isSharedMultiHall" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."schedule_items_weektype_enum" AS ENUM('even', 'odd')`);
        await queryRunner.query(`CREATE TABLE "schedule_items" ("id" SERIAL NOT NULL, "scheduleId" integer NOT NULL, "subjectId" integer NOT NULL, "subgroupId" integer, "lessonTypeId" integer NOT NULL, "teacherId" integer, "roomId" integer, "dayOfWeek" smallint NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "weekType" "public"."schedule_items_weektype_enum", "comment" text, "weekStart" date NOT NULL, "isDisabled" boolean NOT NULL DEFAULT false, "isSameCellParallel" boolean NOT NULL DEFAULT false, "teacherPosition" character varying, "legacyTeacherName" character varying, CONSTRAINT "PK_035b2d214f67bd7ef775cb44ab1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subgroups" ("id" SERIAL NOT NULL, "groupId" integer NOT NULL, "number" smallint NOT NULL, CONSTRAINT "UQ_96144b4d1e5a7f176bf58b995b8" UNIQUE ("groupId", "number"), CONSTRAINT "PK_954128ba413efeb6f9ed12a3f64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."groups_educationform_enum" AS ENUM('full_time', 'part_time', 'distance')`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "directionId" integer NOT NULL, "course" smallint NOT NULL, "educationForm" "public"."groups_educationform_enum" NOT NULL, CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."student_profiles_educationform_enum" AS ENUM('full_time', 'part_time', 'distance')`);
        await queryRunner.query(`CREATE TABLE "student_profiles" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "groupId" integer NOT NULL, "subgroupId" integer, "course" smallint NOT NULL, "educationForm" "public"."student_profiles_educationform_enum" NOT NULL, CONSTRAINT "UQ_064d129936a1e821d637ee8c88e" UNIQUE ("userId"), CONSTRAINT "REL_064d129936a1e821d637ee8c88" UNIQUE ("userId"), CONSTRAINT "PK_5ed0a32eeaddfe812fb326177d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "staff_profiles" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "departmentId" integer NOT NULL, "position" character varying NOT NULL, "cabinet" character varying, CONSTRAINT "UQ_538ab8c582b6c827244952a2923" UNIQUE ("userId"), CONSTRAINT "REL_538ab8c582b6c827244952a292" UNIQUE ("userId"), CONSTRAINT "PK_6d4c6c0b447e39147b4a6dcbede" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "departments" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "shortName" character varying, "headUserId" integer, CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teacher_profiles" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "departmentId" integer NOT NULL, "position" character varying NOT NULL, "cabinet" character varying, CONSTRAINT "UQ_c30bc3401758faae4415391ea23" UNIQUE ("userId"), CONSTRAINT "REL_c30bc3401758faae4415391ea2" UNIQUE ("userId"), CONSTRAINT "PK_fdd17d62015e40674217a407484" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "login" character varying NOT NULL, "passwordHash" character varying NOT NULL, "roleId" integer NOT NULL, "surname" character varying NOT NULL, "name" character varying NOT NULL, "patronymic" character varying NOT NULL, "photoUrl" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2d443082eccd5198f95f2a36e2c" UNIQUE ("login"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "endpoint" text NOT NULL, "p256dh" character varying NOT NULL, "auth" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0008bdfd174e533a3f98bf9af16" UNIQUE ("endpoint"), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('schedule', 'consultation')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "payload" jsonb, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "consultation_notification_preferences" ("userId" integer NOT NULL, "enabled" boolean NOT NULL DEFAULT false, "allTeachers" boolean NOT NULL DEFAULT true, "teacherIds" jsonb NOT NULL DEFAULT '[]', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf198de7f5efd4885de57cd0c4c" PRIMARY KEY ("userId"))`);
        await queryRunner.query(`CREATE TABLE "schedule_preholiday_days" ("id" SERIAL NOT NULL, "date" date NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d62c2623eec9a2af068752c6149" UNIQUE ("date"), CONSTRAINT "PK_6fdedb907acee868e925c629c5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "consultations" ("id" SERIAL NOT NULL, "departmentId" integer NOT NULL, "teacherId" integer NOT NULL, "subject" character varying NOT NULL, "consultationType" character varying NOT NULL, "dayOfWeek" smallint NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "weekStart" date NOT NULL, "room" character varying, "comment" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c5b78e9424d9bc68464f6a12103" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_uploads" ADD CONSTRAINT "FK_063708332777731acc664274d59" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_a34fb9d75013c4d3ae96ef331c4" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_6762535c8134c5e8314ea862e4b" FOREIGN KEY ("uploadId") REFERENCES "schedule_uploads"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_d53e9c0b8f2c83ecaf15c9c4e60" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_items" ADD CONSTRAINT "FK_b11aed01275fee4c24d6da5069c" FOREIGN KEY ("scheduleId") REFERENCES "schedules"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_items" ADD CONSTRAINT "FK_851a89ea7917af326bc45556315" FOREIGN KEY ("subjectId") REFERENCES "subjects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_items" ADD CONSTRAINT "FK_11cc27365f3d9e635199e73c839" FOREIGN KEY ("subgroupId") REFERENCES "subgroups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_items" ADD CONSTRAINT "FK_bb18457a45188b41400afdfb2b8" FOREIGN KEY ("lessonTypeId") REFERENCES "lesson_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_items" ADD CONSTRAINT "FK_94e22d01cb83c7ecd838cc09680" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedule_items" ADD CONSTRAINT "FK_6ef19061baa7682420ffe87c7a4" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subgroups" ADD CONSTRAINT "FK_e1da74d9e5dd6edf73ecfbd8abd" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_5bdd0eab540bb13c33c07a764ff" FOREIGN KEY ("directionId") REFERENCES "directions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_profiles" ADD CONSTRAINT "FK_064d129936a1e821d637ee8c88e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_profiles" ADD CONSTRAINT "FK_98ad5dd88508a4c7254b1a7a277" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "student_profiles" ADD CONSTRAINT "FK_9ac6404341095453baa49e2400f" FOREIGN KEY ("subgroupId") REFERENCES "subgroups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_538ab8c582b6c827244952a2923" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_6a38bb2ec55a601253799c2238e" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_69025af2ac3cdaa692608056ed9" FOREIGN KEY ("headUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_profiles" ADD CONSTRAINT "FK_c30bc3401758faae4415391ea23" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teacher_profiles" ADD CONSTRAINT "FK_cb0230ca75ff100a74f3d2bcc97" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_4cc061875e9eecc311a94b3e431" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultation_notification_preferences" ADD CONSTRAINT "FK_cf198de7f5efd4885de57cd0c4c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultations" ADD CONSTRAINT "FK_77c8f6dddaa4de87d72427b98da" FOREIGN KEY ("departmentId") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultations" ADD CONSTRAINT "FK_bd2d65b06301efd13e9d22b003f" FOREIGN KEY ("teacherId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "consultations" DROP CONSTRAINT "FK_bd2d65b06301efd13e9d22b003f"`);
        await queryRunner.query(`ALTER TABLE "consultations" DROP CONSTRAINT "FK_77c8f6dddaa4de87d72427b98da"`);
        await queryRunner.query(`ALTER TABLE "consultation_notification_preferences" DROP CONSTRAINT "FK_cf198de7f5efd4885de57cd0c4c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_4cc061875e9eecc311a94b3e431"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "teacher_profiles" DROP CONSTRAINT "FK_cb0230ca75ff100a74f3d2bcc97"`);
        await queryRunner.query(`ALTER TABLE "teacher_profiles" DROP CONSTRAINT "FK_c30bc3401758faae4415391ea23"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_69025af2ac3cdaa692608056ed9"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_6a38bb2ec55a601253799c2238e"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_538ab8c582b6c827244952a2923"`);
        await queryRunner.query(`ALTER TABLE "student_profiles" DROP CONSTRAINT "FK_9ac6404341095453baa49e2400f"`);
        await queryRunner.query(`ALTER TABLE "student_profiles" DROP CONSTRAINT "FK_98ad5dd88508a4c7254b1a7a277"`);
        await queryRunner.query(`ALTER TABLE "student_profiles" DROP CONSTRAINT "FK_064d129936a1e821d637ee8c88e"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_5bdd0eab540bb13c33c07a764ff"`);
        await queryRunner.query(`ALTER TABLE "subgroups" DROP CONSTRAINT "FK_e1da74d9e5dd6edf73ecfbd8abd"`);
        await queryRunner.query(`ALTER TABLE "schedule_items" DROP CONSTRAINT "FK_6ef19061baa7682420ffe87c7a4"`);
        await queryRunner.query(`ALTER TABLE "schedule_items" DROP CONSTRAINT "FK_94e22d01cb83c7ecd838cc09680"`);
        await queryRunner.query(`ALTER TABLE "schedule_items" DROP CONSTRAINT "FK_bb18457a45188b41400afdfb2b8"`);
        await queryRunner.query(`ALTER TABLE "schedule_items" DROP CONSTRAINT "FK_11cc27365f3d9e635199e73c839"`);
        await queryRunner.query(`ALTER TABLE "schedule_items" DROP CONSTRAINT "FK_851a89ea7917af326bc45556315"`);
        await queryRunner.query(`ALTER TABLE "schedule_items" DROP CONSTRAINT "FK_b11aed01275fee4c24d6da5069c"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_d53e9c0b8f2c83ecaf15c9c4e60"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_6762535c8134c5e8314ea862e4b"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_a34fb9d75013c4d3ae96ef331c4"`);
        await queryRunner.query(`ALTER TABLE "schedule_uploads" DROP CONSTRAINT "FK_063708332777731acc664274d59"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`DROP TABLE "consultations"`);
        await queryRunner.query(`DROP TABLE "schedule_preholiday_days"`);
        await queryRunner.query(`DROP TABLE "consultation_notification_preferences"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "teacher_profiles"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP TABLE "staff_profiles"`);
        await queryRunner.query(`DROP TABLE "student_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."student_profiles_educationform_enum"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TYPE "public"."groups_educationform_enum"`);
        await queryRunner.query(`DROP TABLE "subgroups"`);
        await queryRunner.query(`DROP TABLE "schedule_items"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_items_weektype_enum"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
        await queryRunner.query(`DROP TABLE "lesson_types"`);
        await queryRunner.query(`DROP TYPE "public"."lesson_types_code_enum"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP TYPE "public"."schedules_scheduletype_enum"`);
        await queryRunner.query(`DROP TABLE "schedule_uploads"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_uploads_parsestatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."schedule_uploads_scheduletype_enum"`);
        await queryRunner.query(`DROP TABLE "directions"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_code_enum"`);
    }

}
